// <auto-generated />
using System;
using Estoque_Caixa.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstoqueCaixa.Migrations
{
    [DbContext(typeof(OrganizadorContext))]
    [Migration("20230206210240_CriacaoTabelaEstoqueCaixa")]
    partial class CriacaoTabelaEstoqueCaixa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Estoque_Caixa.Models.PedidoVenda", b =>
                {
                    b.Property<int>("PedidoVendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoVendaId"));

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusPedido")
                        .HasColumnType("int");

                    b.HasKey("PedidoVendaId");

                    b.ToTable("PedidoVendas");
                });

            modelBuilder.Entity("Estoque_Caixa.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodBarras")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PedidoVendaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnit")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("StatusProduto")
                        .HasColumnType("int");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoVendaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Estoque_Caixa.Models.Produto", b =>
                {
                    b.HasOne("Estoque_Caixa.Models.PedidoVenda", null)
                        .WithMany("Produtos")
                        .HasForeignKey("PedidoVendaId");
                });

            modelBuilder.Entity("Estoque_Caixa.Models.PedidoVenda", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
